name: PrivaStream Public CI

on:
  push:
    branches: [ "public" ]
  pull_request:
    branches: [ "public" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Basic Pre-flight check
      run: echo "Verificando integridad del código sanitizado publicado..."
